# - DESAFIO 012: FAÇA UM ALGORITMO QUE LEIA O PREÇO DE UM PRODUTO E MOSTRE SEU NOVO PREÇO
# COM 5% DE DESCONTO -
p=float(input(f'VAMOS CALCULAR QUANTO FICA O SEU PRODUTO APÓS O CUPOM 5% DE DESCONTO\n'
              f'QUAL O VALOR DO PRODUTO? '))

c=(float(5/100))
d=(float(p*c))
t=(float(p-d))
print(f'O SEU PRODUTO DE R${p:.2f}, FICA POR R${t:.2f} COM O CUPOM DE 5% DE DESCONTO!')
