# - DESAFIO 013.5: FAÇA UM PROGRAMA QUE LEIA O VALOR DE UM PRODUTO E INFORME O SEU VALOR À VISTA
# COM DESCONTO E À PRAZO COM AUMENTO!
v = float (input (f'O PAGAMENTO DO PRODUTO À VISTA TEM UM DESCONTO DE 10% E PARCELADO TEM 8% DE AUMENTO\n'
                  f'QUAL O VALOR DESTE PRODUTO? '))
d = v*(10/100)
a = v*(8/100)
print(f' O VALOR DO SEU PRODUTO É DE R${v:.2f}!\n'
           f'O VALOR À VISTA É DE:R${v-d:.2f}!\n'
           f'O VALOR À PRAZO É DE:R${v+a:.2f}!\n'
           f'COM UM PARCELAMENTO DE ATÉ 3X S/JUROS NO VALOR DE: R${(v+a)/3:.2f} MENSAIS!')