# - DESAFIO 017: FAÇA UM PROGRAMA QUE LEIA O COMPRIMENTO DO CATETO OPOSTO E DO ADJACENTE DE UM
# TRIANGULO RETÂNGULO. CALCULE E MOSTRE A HIPOTENUSA! -

from math import hypot

c = float (input('ME INFORME OS CATETOS PARA QUE EU CALCULE A HIPOTENUSA!\n'
          'CATETO OPOSTO: '))
c2 = float (input ('CATETO ADJACENTE: '))

h = hypot(c,c2)

print(f'A HIPOTENUSA é {h:.2f}!')
