# - Desafio 020: O MESMO PROFESSOR DO DESAFIO ANTERIOR QUER SORTEAR A ORDEM DE APRESENTAÇÃO DE TRABALHOS DOS ALUNOS.
# FAÇA UM PROGRAMA QUE LEIA O NOME DOS QUATRO ALUNOS E MOSTRE A ORDEM SORTEADA! -

from random import shuffle

a1 = input ('INFORME O PRIMEIRO ALUNO: ')
a2 = input ('INFORME O SEGUNDO ALUNO: ')
a3 = input ('INFORME O TERCEIRO ALUNO: ')
a4 = input ('INFORME O QUARTO ALUNO: ')
lista = [a1,a2,a3,a4]
shuffle (lista)

print(f'A ORDEM DE APRESENTAÇÃO SERA: {lista}!')