# - DESAFIO 006: CRIE UM ALGORÍTMO QUE LEIA UM NÚMERO E MOSTRE O SEU DOBRO, TRIPLO E RAÍZ QUADRADA
n1=int(input(f'Ô ZOREIÚDO! QUAL NÚMERO VOCÊ QUER SABER O SEU DOBRO, TRIPLO E A RAÍZ QUADRADA? '))
print(f'O NÚMERO QUE VOCÊ ME INFORMOU É: {n1}!\n'
      f'O SEU DOBRO É: {n1*2}!\n'
      f'O SEU TRIPLO É: {n1*3}!\n'
      f'E A RAÍZ É:{n1**(1/2):.2f}!\n'
      f'PELAMOR DE DEUS, RATO BRANCO!')
