#-AULA 07: OPERADORES ARITMÉTICOS-
# SUBTRAÇÃO (-)
# ADIÇÃO (+)
# DIVISÃO (/)
# MULTIPLICAÇÃO (*)
# POTENCIAÇÃO (**)
# DIVISÃO INTEIRA(//)
# RESTO DA DIVISÃO (%)
#- ORDEM DE PRECEDÊNCIA:
# 1º"()"
# 2º"**"
# 3º"*,/,//,%" (SE HOUVEREM TODOS, RESOLVE-SE O QUE ESTIVER EM PRIMEIRO)
# 4º"+,-"