# DESAFIO 026: FAÇA UM PROGRAMA QUE LEIA UMA FRASE PELO TECLADO E MOSTRE:
# a) QUANTAS VEZES APARECE A LETRA "A"
# b) EM QUE POSIÇÃO ELA APARECE A PRIMEIRA VEZ
# c) EM QUE POSIÇÃO ELA APARECE A ÚLTIMA VEZ -