#4**3==64
#pow(4,3)==64
#SÓ QUE QUANDO USAMOS A FUNÇÃO 'pow' PERDEMOS A ORDEM DE PRECEDÊNCIA
#81**(1/2)==9.0 AO COLOCAR '**' (ELEVADO Á) 1/2 CALCULAMOS A RAIZ QUADRADA DO NÚMERO
#POIS A RAIZ É O MESMO QUE O NUMERO ELEVADO À (1/2)
#A RAIZ CUBICA É **(1/3)

print(f'VOU MOSTRAR TODAS OS OPERADORES NUMÉRICOS PRA VOCÊ, DE ACORDO COM OS NUMEROS INSERIDOS!')
x = int(input('O PRIMEIRO NÚMERO É:'))
y = int(input('O SEGUNDO NÚMERO É:'))
a=x+y
s=x-y
d=x/y
m=x*y
di=x//y
rd=x%y
p=x**y
print(f'OS RESULTADOS SÃO\nADIÇÃO:{a}\nSUBTRAÇÃO:{s}\nDIVISÃO:{d}\nMULTIPLICAÇÃO:{m}\nDIVISÃO INTEIRA:{di}\nRESTO DE DIVISÃO:{rd}\nE POR FIM, POTENCIAÇÃO:{p}')

