# QUALQUER FRASE É UMA 'CADEIA DE CARACTÉRES' ou STRING E ESTA SEMPRE ENTRE ASPAS SIMPLES OU DUPLAS
from pydoc import stripid

frase = 'Curso em Video Python'
# O PYTHON CRIA MINI ESPAÇOS E EM CADA UM DELES VAI UM CARACTERE (ESPAÇOS DO TECLADO TAMBÉM SÃO CARACTÉRES)

#FATIAMENTO (ESSE VALOR ENTRE COLCHETES '[]' SE CHAMA 'RANGE')
# (O COLCHETE '[]' É UTILIZADO PARA IDENTIFICAR LISTAS)
print (frase[9]) #MOSTRA O CARACTERE nº:9
print (frase[9:13]) #MOSTRA DO CARACTERE Nº:9 AO Nº:12 (ELE EXCLUI O 13)
print (frase[9:21]) #MOSTRA DO CARACTERE Nº 9 AO Nº 20 (MESMA LÓGICA)
print (frase[9:21:2]) #MOSTRA DO Nº9 AO Nº 20 PULANDO DE 2 EM 2
print (frase[:5]) #COMO NÃO TEM NUMERO ANTES DO ':' ELE COMEÇA DO INICIO ATÉ O Nº4
print (frase[15:]) # ELE COMEÇA DO 15 E VAI ATÉ O FIM, POIS NÃO DEFINIMOS Nº APÓS ':'
print (frase[9::3]) # ELE COMEÇA DO 9 ATÉ O FINAL (NÃO TEM VALOR NO MEIO DOS PONTOS) PULANDO DE 3 EM 3

#ANÁLISE
#len "LENGTH"(frase)
print (len(frase)) # A 'FRASE' TEM 21 CARACTÉRES
print (frase.count('o')) #CONTA QUANTAS VEZES O 'o' APARECE NA FRASE
print (frase.count('o',0,13)) #CONTA QUANTAS VEZES O 'o' APARECE DO CARAC. "0" AO "12"
print (frase.find('deo')) #MOSTRA EM QUAL CARACTERE COMEÇA O 'deo'
print (frase.find('ANDROID')) #MOSTRA '-1' PORQUE COMEÇANDO PELO '0' NÃO HÁ ESSA STRING, ENTÃO: -1 (ANTES DE COMEÇAR A 'frase')
print ('Curso' in frase) #MOSTRA SE HÁ ESSE TERMO NA 'FRASE' (DIFERENCIA UPPER DE LOWER)

#TRANSFORMAÇÃO
#VIA DE REGRA UMA LISTA DE STRING É IMUTÁVEL SENÃO POR METODOS
print (frase.replace('Python','Android')) #SUBSTITUI O "old" PELO "new"
print (frase.upper()) #DEIXA EM MAIÚSCULO
print (frase.lower()) #DEIXA EM MINÚSCULO
print (frase.capitalize()) #DEIXA APENAS A LETRA INICIAL DA FRASE EM MAIÚSCULO
print (frase.title()) #DEIXA AS LETRAS INICIAIS DE TODAS AS PALAVRAS MAIÚSCULAS (SE ORIENTA PELOS ESPAÇOS)
print ('   APRENDA PYTHON   '.strip()) #REMOVE TODOS OS ESPAÇOS 'INUTEIS' DA STRING
print ('   APRENDA PYTHON   '.rstrip()) #REMOVE ESPAÇOS 'INUTEIS' À DIREITA
print ('   APRENDA PYTHON   '.lstrip()) #REMOVA OS ESPAÇOS À ESQUERDA

#DIVISÃO
print (frase.split()) #REMOVE OS ESPAÇOS

#JUNÇÃO
print ('-'.join(frase))

#EXEMPLO EM AULA:
print (frase.upper().count('O')) #COLOQUEI A FRASE EM MAIÚSCULA E MANDEI CONTAR O 'O'
print (len('     '+frase+'       '.strip())) #QUIS SABER O LENGTH DA STRING APÓS CORTAR OS ESPAÇOS INDESEJADOS

divido = frase.split()
print (divido[0]) # PEDI PARA MOSTRAR O ITEM '0' DA LISTA 'FRASE DIVIDIDA'
print(divido[2][3]) # PEDI PARA MOSTRAR O TERCEIRO CARACTERE DO SEGUNDO ITEM DA LISTA FRASE DIVIDIDA(ITEN É 'video')
frase.