# - DESAFIO 007: DESENVOLVA UM PROGRAMA QUE LEIA AS DUAS NOTAS DE UM ALUNO, CALCULE E MOSTRE A SUA MÉDIA
n1=float(input(f'QUANTO QUE VOCÊ TA TIRANDO DE MÉDIA, ZÉ RUELA? ME FALA A SUA PRIMEIRA NOTA: '))
n2=float(input(f'A SEGUNDA NOTA:'))
n3=(n1+n2)/2
print(f'A SUA PRIMEIRA NOTA FOI: {n1}!\n'
      f'A SUA SEGUNDA NOTA FOI: {n2}!\n'
      f'A SUA MEDIA ENTÃO FOI: {n3}!\n'
      f'MEUA MIGO...')