# - DESAFIO 005: FAÇA UM PROGRAMA QUE LEIA UM NÚMERO INTEIRO E MOSTRE O SEU SUCESSOR E ANTECESSOR!
print(f'EAE OREIA SECA! DIGITA UM NUMERO, AÍ QUE EU MOSTRO O SEU SUCESSOR E SEU ANTECESSOR!\n'
      f'VOCÊ NÃO SABE NEM ISSO? XD ')
n1=int(input('DIGITA AE! '))
print(f'O NÚMERO QUE VOCÊ DIGITOU É: {n1}!\n'
      f' O SEU SUCESSOR É: {n1+1}!\n'
      f' E O SEU ANTECESSOR É: {n1-1}!\n'
      f' E VOCÊ É: OREIA SECA!')