# - DESAFIO 010: CRIE UM PROGRAMA QUE LEIA QUANTO DINHEIRO UMA PESSOA TEM NA CARTEIRA E MOSTRE A QUANTOS DÓLARES EQUIVALE:
# CONSIDERE DÓLAR US$1.00 == R$3.27 (DESAFIO PESSOAL: FAZER COM O DÓLAR ATUAL) -
numero01=n1=float(input(f'VOCÊ QUER SABER QUANTOS DÓLARES DARIAM SEUS R$?\n SEM PROBLEMAS! QUANTOS R$ VOCÊ TEM? '))
numero02=n2=float(n1*(1/6.16))
numero03=n3=float(n1*(1/5.58))
print(f'OS SEUS R${n1:.2f} EQUIVALEM À €{n2:.2f} EUROS E US${n3:.2f} DOLARES')